# Defaults/explanation:
#
# pkonly: true		[true/false]	When true trophies only drop when a player kills another player (as opposed to self drowning, etc)
# droprate: 0.05	[0.0 -> 1.0]	Chance that a trophy will drop when a player dies (1 is 100%, 0 is never)
# hookbreak: true	[true/false]	When true breaking head blocks will drop the correct player, instead of Steve
#

pkonly: true
droprate: 0.05
hookbreak: true
