name: PlayerHeads
version: 0.1.0005
description: Drops a player's head when s/he dies
author: meiskam

main: org.shininet.bukkit.PlayerHeads.PlayerHeads
database: false

commands:
  PlayerHeads:
    description: Spawn a playerhead or edit playerheads config
    aliases: ph
    
permissions:
  playerheads:
    description: Gives all PlayerHeads permissions
    children:
      playerheads.droprate: true
      playerheads.spawn: true
  playerheads.config:
    description: Allows user to edit, save, or reload configs
    children:
      playerheads.config.view: true
      playerheads.config.edit: true
  playerheads.config.get:
    description: Allows user to get configs
    default: op
  playerheads.config.set:
    description: Allows user to set or reload configs
    default: op
  playerheads.spawn:
    description: Spawn a player head
    default: op
    children:
      playerheads.spawn.own: true
  playerheads.spawn.own:
    description: Spawn your own head
    default: op
